# syntax=docker/dockerfile:1

FROM python:3-slim-bullseye

WORKDIR /app

RUN apt update && apt upgrade -y 

RUN pip3 install flask && pip3 install opentelemetry-distro && pip3 install opentelemetry-instrumentation \
    && opentelemetry-bootstrap --action=install && pip3 install opentelemetry-exporter-otlp

COPY sample_flask_app_otel.py /app

CMD ["opentelemetry-instrument", "python3", "sample_flask_app_otel.py"]

