# base values file at https://github.com/DataDog/helm-charts/blob/main/charts/datadog/values.yaml
datadog:
  apiKeyExistingSecret: datadog-secret
  appKeyExistingSecret: datadog-secret

  # just a tag
  clusterName: otel-ddot-testbed

  kubelet:
    # aks true, eks true, kubeadm false
    tlsVerify: true
    # for aks
    #host:
    #  valueFrom:
    #    fieldRef:
    #      fieldPath: spec.nodeName
    #hostCAPath: /etc/kubernetes/certs/kubeletserver.crt
  
  apm:
    socketEnabled: true
    portEnabled: true
    peer_tags_aggregation: true
    compute_stats_by_span_kind: true
    peer_service_aggregation: true
    instrumentation:
      enabled: true
      # example, don't pin to latest
      libVersions:
        python: latest

  orchestratorExplorer:
    enabled: true

  logs:
    enabled: true
    containerCollectAll: true
    autoMultiLineDetection: true

  # required for live container view
  processAgent:
    enabled: true
    processCollection: true
    processDiscovery: true

    env:
    - name: DD_HOSTNAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName

  # dd agent with embedded otel collector / dd exporter
  otelCollector:
    enabled: true
    ports:
      - containerPort: "4317"
        hostPort: "4317"
        name: otel-grpc

agents:
  image:
    repository: gcr.io/datadoghq/agent
    tag: 7.65.0-full
    doNotCheckTag: true

providers:
  aks:
    enabled: false
